---
- name: Setup the secrets for deploy keys
  hosts: secrets
  vars:
    jenkins:
      name: github-jenkins
      ssh_private_key: "{{ jenkins_private_key }}"
    spring:
      name: github-spring
      ssh_private_key: "{{ spring_private_key }}"
    vue:
      name: github-vue
      ssh_private_key: "{{ vue_private_key }}"
  tasks:
    - include_vars: "{{ playbook_dir }}/deploy-keys/keys.yml"
    - name: replace secret params with variables
      template:
        src: "{{ playbook_dir }}/params/secrets/secret.j2"
        dest: "{{ playbook_dir }}/params/secrets/{{ item.name }}"
      with_items:
        - "{{ jenkins }}"
        - "{{ spring }}"
        - "{{ vue }}"
    - include_role:
        name: openshift-applier/roles/openshift-applier
